### ISSUE TITLE
hdparam does not work on sas drives .

### ISSUE THREAD

**Issue by augustynr** [efnats/chiamerge#1]
Hi thank you for the scripts, very nice.
Couple enhancements: hdparm does not work on sas drives but
```
 smartctl -i ${DEVICE} | grep -i "Serial Number" | awk  '{ print $3 }'
```
does work for both types.
the script has problems with dealing with more then sda-sdz devices.
I have sdaa-sdaz and so on ...

You may consider using parted instead of fdisk and have an option to use xfs.
Once again thank you!

**Comment by efnats** [comment]
Thank you!

I chose hdparm, because smarctl does not work well on usb drives. I guess the correct way is to detect wether its a SAS or USB drive and then apply the correct method. I will test your code and update the script in one of the next releases. Can you give me a hint on what to look out for to reliably detect wether a drive is an SAS drive?

It's correct, that extended drive letters are currently not working. I tried it, but failed. What should work though is `sda-sdz, sdaa-sdaz`
I have stopped further investigating this because it is planned in a later version to get the drive list from lsblk, apply a filter (for example by drive size) and then write this into an array.

I think xfs is not dependant on the partitionning programm afaik. It should be possible to mkfs.xfs on the drive. Good idea. I will add support for xfs.

Thanks again for testing this. You are the first one who's giving me feedback. I appreciate.

**Comment by augustynr** [comment]
Look for transport protocol:
sudo smartctl -i /dev/sdt
smartctl 7.1 2019-12-30 r5022 [x86_64-linux-5.4.0-89-generic] (local build)
Copyright (C) 2002-19, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Vendor:               HGST
Product:              HUH721010AL4200
Revision:             A21D
Compliance:           SPC-4
User Capacity:        10,000,831,348,736 bytes [10.0 TB]
Logical block size:   4096 bytes
LU is fully provisioned
Rotation Rate:        7200 rpm
Form Factor:          3.5 inches
Logical Unit id:      0x5000cca26c0466f0
Serial number:        1DG2E1LZ
Device type:          disk
Transport protocol:   SAS (SPL-3)
Local Time is:        Mon Nov  8 20:08:45 2021 EST
SMART support is:     Available - device has SMART capability.
SMART support is:     Enabled
Temperature Warning:  Enabled

**Comment by augustynr** [comment]
One problem I have is that using the drive names sd* is not consistent.
If you make any changes to the system, it will move  drives around
The only  consistent way is to use uuid. That makes it much safer

**Comment by efnats** [comment]
The idea of the entire mount.service is that you never have to worry about sd*.
You will only need to specify sd* with chiaman for the time when you are preparing (formatting + labelling) your disks.
after that all disks are mounted by label which in this specific case does not change, as the drives are labelled by their serial name

**Comment by efnats** [comment]
> Look for transport protocol: sudo smartctl -i /dev/sdt smartctl 7.1 2019-12-30 r5022 [x86_64-linux-5.4.0-89-generic] (local build) Copyright (C) 2002-19, Bruce Allen, Christian Franke, [www.smartmontools.org](http://www.smartmontools.org)
> 
> === START OF INFORMATION SECTION === Vendor: HGST Product: HUH721010AL4200 Revision: A21D Compliance: SPC-4 User Capacity: 10,000,831,348,736 bytes [10.0 TB] Logical block size: 4096 bytes LU is fully provisioned Rotation Rate: 7200 rpm Form Factor: 3.5 inches Logical Unit id: 0x5000cca26c0466f0 Serial number: 1DG2E1LZ Device type: disk Transport protocol: SAS (SPL-3) Local Time is: Mon Nov 8 20:08:45 2021 EST SMART support is: Available - device has SMART capability. SMART support is: Enabled Temperature Warning: Enabled

Thanks, that is helpful! I will implement support for SAS drives in one of the next releases.

**Comment by efnats** [comment]
I am about to implement support for xfs now. What xfs formatting options do you recommend?

**Comment by augustynr** [comment]
Something like this works for me ... though I am not sure if that is the best :)
 format_xfs()
{
for i in "$@"
do
DEVICE=/dev/${i}

# If the device is already mounted, don't perform any destructive action on it
# lsblk -n ${DEVICE} -l -o mountpoint | grep ${i} && echo "Disk ${DEVICE} is mounted on ${MOUNTPOINT} - ignoring disk."; continue

# Partition the Disk
echo -n "${i}..."

case ${DEBUGLEVEL} in
0) parted ${DEVICE} --align=optimal --script mklabel gpt mkpart primary xfs 0% 100% >  /dev/null  2>&1
   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}NOT OK${NOCOLOR}";;

1) parted ${DEVICE} --align=optimal --script mklabel gpt mkpart primary xfs 0% 100% >> ${LOGFILE} 2>&1 
   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}NOT OK${NOCOLOR}";;
esac

# Get serial number of Disk
SERIALNR=$(smartctl -i ${DEVICE} | grep -i "Serial Number" | awk  '{ print $3 }')

                # Create filesystem xfs for large files, no reserved space and label partition
echo -n "mkfs on ${i}..."

case ${DEBUGLEVEL} in
0) mkfs.xfs -f -L "${SERIALNRPREFIX}${SERIALNR}" ${DEVICE} >  /dev/null  2>&1
   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}NOT OK${NOCOLOR}";;

1) mkfs.xfs -f  -L "${SERIALNRPREFIX}${SERIALNR}" ${DEVICE} >> ${LOGFILE} 2>&1 
   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}NOT OK${NOCOLOR}";;
esac

echo ""
done
}
label_xfs()
{
for i in "$@"
do
        DEVICE=/dev/${i}

# Get serial number of disk
SERIALNR=$(smartctl -i ${DEVICE} | grep -i "Serial Number" | awk  '{ print $3 }')

# Label the partition
echo -n "${i}..."

case ${DEBUGLEVEL} in
0) xfs_admin -L "${SERIALNRPREFIX}${SERIALNR}" ${DEVICE} >  /dev/null   2>&1 
   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}NOT OK${NOCOLOR}";;

1) xfs_admin -L "${SERIALNRPREFIX}${SERIALNR}" ${DEVICE} >> ${LOGFILE}  2>&1 
   test $? -eq 0 && echo -e "${GREEN}OK${NOCOLOR}" || echo -e "${RED}NOT OK${NOCOLOR}";;
esac
done
}

 




Sincerely,


Robert Augustyn


p:519.997.3106 ext:802


m:519.817.2503


http://www.linqone.com








-----Original message-----

**Comment by efnats** [comment]
I tested this again and I noticed, that smartctl does read out the correct serialnr of a connected usb drive. So there we go. All works now with the suggested bash line. Thanks a lot Robert.

Support for xfs was added, too btw. Check the configuration settings in the script.
