### ISSUE TITLE
installation fails on ubuntu 20.04

### ISSUE THREAD

**Issue by augustynr** [efnats/chiamerge#2]
root@chiaserver:~/chiamerge-main# ./install.sh 

Welcome to chia-tools install script

This will install prerequesites and copy the mnt-garden.mount to your systemd folder and reload the systemd daemon
The rest can be found in /usr/local/bin/

Continue? (y/n)y

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package udisks is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'udisks' has no installation candidate
cp: cannot stat 'mnt.garden.mount': No such file or directory
'mount-chia-drives.service' -> '/etc/systemd/system/mount-chia-drives.service'
'chia-mountall' -> '/usr/local/bin/chia-mountall'
'chia-unmountall' -> '/usr/local/bin/chia-unmountall'
'chiaman' -> '/usr/local/bin/chiaman'
Failed to enable unit: Unit file mnt-garden.mount does not exist.
done

**Comment by efnats** [comment]
thank you. there was a typo in the install.sh. it is fixed now.
