### ISSUE TITLE
problem mounting directory

### ISSUE THREAD

**Issue by augustynr** [efnats/chiamerge#4]
./chia-mountall 
Error connecting to the udisks daemon: Could not connect: No such file or directory
Error connecting to the udisks daemon: Could not connect: No such file or directory
Error connecting to the udisks daemon: Could not connect: No such file or directory
Error connecting to the udisks daemon: Could not connect: No such file or directory
Error connecting to the udisks daemon: Could not connect: No such file or directory
Error connecting to the udisks daemon: Could not connect: No such file or directory
Error connecting to the udisks daemon: Could not connect: No such file or directory
Error connecting to the udisks daemon: Could not connect: No such file or directory
Error connecting to the udisks daemon: Could not connect: No such file or directory

**Comment by efnats** [comment]
are you root?

**Comment by augustynr** [comment]
yes

**Comment by augustynr** [comment]
udisksctl status
Error connecting to the udisks daemon: Could not connect: No such file or directory

**Comment by efnats** [comment]
it's hard to say from here. what version of udisks do you have installed? can you check with aptitude if you can manually install a newer version?

**Comment by augustynr** [comment]
thx, it looks like it is working now, I have added some HDs and move the connection arround.
After the reboot it looks ok.
Sorry for the bothering you. :)

**Comment by efnats** [comment]
No worries! I am very excited that someone is using this.
